### ISSUE TITLE
Failed to load checkpoint

### ISSUE THREAD

**Issue by CheungBH** [LeapLabTHU/AdaFocusV2#2]
Hello. Thanks for your code. I am currently running your testing code, but I failed to load the checkpoint of global CNN mobilenet_v2. 
ValueError: unknown url type: '/cluster/home2/yueyang/.cache/torch/hub/checkpoints/mobilenetv2_1.0-f2a8633.pth.tar'
Could I know where can I find the corresponding checkpoint file?

**Comment by yueyang2000** [comment]
This link will fix your problem:

https://www.dropbox.com/s/47tyzpofuuyyv1b/mobilenetv2_1.0-f2a8633.pth.tar?dl=1
