### ISSUE TITLE
about results of sthv1

### ISSUE THREAD

**Issue by zzzhhh1031** [LeapLabTHU/AdaFocusV2#4]
Hello, thank you for your great work! I reproduced the results on sthv1 using the command-line arguments you gave (patch size 128), and the best evaluation result was only 46.4, which is lower than the 47.0 given in your paper, What is the reason for this? Thank you!

**Comment by yueyang2000** [comment]
It's possible that your dataset preprocessing pipeline is different from ours. Here's the inference output of sthv1_p128.pth.tar on our machine.

[output.log](https://github.com/LeapLabTHU/AdaFocusV2/files/10177675/output.log)
